---
title: "plots"
output:
  html_document: default
  pdf_document: default
date: '2023-05-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install packages}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(hrbrthemes)
library(viridis)
```

read in csv data

```{r read file, echo=FALSE}
data <- read.csv('example_data_for_visualization.csv')
```

density plot: distribution of vowel duration by gender
```{r densityplot, fig.cap = paste("Density distribution of vowel duration by gender")}
data %>% ggplot(aes(x = vdur,group = gender,
                                    fill = gender,
                                    colour = gender))+
  geom_density(alpha = 0.5) +
theme(text = element_text(size = 20)) ##change text size density_plot

```


scatterplot: scatterplot between speaking rate and F0.
```{r plot fig.cap = "Relationship between speaking rate and useF0"}
##scatter plot
data %>% ggplot(aes(x = spk_rate, y = usef0))+ geom_point(size = 2) +
geom_smooth(method = "glm") + #adding a smoothed line theme(axis.text=element_text(size=12),
theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold")) +
  xlab("speaking rate") + ylab("f0")
```

```{r box, fig.cap = "A boxplot with jitter VOT across different word labels"}
# Plot
data %>%
  ggplot( aes(x=label, y=vot, fill=label)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
   theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    )+
    ggtitle("A boxplot with jitter") +
    xlab("")
```



```{r boxplot, fig.cap = "Boxplot of VOT across different word labels"}
# Boxplot
data %>%
  ggplot( aes(x=label, y=vot, fill=label)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Basic boxplot") +
    xlab("")
```

```{r barplot, fig.cap="mean VOT across labels"}
ggplot(data, aes(x=label, y=vot)) + 
  geom_bar(stat = "identity")
```  
  
```{r violin, fig.cap = "Violin plot of VOT across different word labels"}
# Violin basic
data %>%
  ggplot( aes(x=label, y=vot, fill=label)) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    ggtitle("Violin chart") +
    xlab("")
```

```{r hex, fig.cap='distribution of usef0 across wdur'}
ggplot(data, aes(x=wdur, y=usef0) ) +
  geom_hex(bins=70) +
  scale_fill_continuous(type = "viridis") +
  theme_bw()
```

